# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
danielle = User.create!(name: 'Danielle')
ferris = User.create!(name: 'Ferris')
troy = User.create!(name: 'Troy')
edgar = User.create!(name: 'Edgar')
t1 = Template.create!(title: 'template title 1', body: 'these are sentences for template title 1. so many sentences. more sentences. sentences.')
t2 = Template.create!(title: 'template title 2', body: 'wow amazing. so cool. love this template.')
t3 = Template.create!(title: 'template title 3', body: 'This is a new sentence. You have never seen sentences like this before. Template 3 sentences. Amazing.')
s1 = Story.create!(template: t1, words: 'words words words cool words amazing words the best words')
s2 = Story.create!(template: t2, words: 'noun verb noun verb adjective otter otter')
s3 = Story.create!(template: t2, words: 'who what when where why')
s4 = Story.create!(template: t3, words: 'new amazing wow cool otter dan class flatiron school')
s5 = Story.create!(template: t3, words: 'awful gross disgusting words no one likes')
s6 = Story.create!(template: t3, words: 'ali sebastian alex evans cool amazing great wow')
s7 = Story.create!(template: t1, words: 'woot woot woot woot woof woof woof woof')
r1 = Recap.create()
r2 = Recap.create()
r3 = Recap.create()
r4 = Recap.create()
r5 = Recap.create()
r6 = Recap.create()
ur1 = UserRecap.create(user: danielle, recap: r1)
ur2 = UserRecap.create(user: danielle, recap: r2)
ur3 = UserRecap.create(user: danielle, recap: r3)
ur4 = UserRecap.create(user: ferris, recap: r4)
ur5 = UserRecap.create(user: troy, recap: r5)
ur6 = UserRecap.create(user: edgar, recap: r6)
rs1 = RecapStory.create(story: s1, recap: r1)
rs2 = RecapStory.create(story: s2, recap: r1)
rs3 = RecapStory.create(story: s3, recap: r1)
rs4 = RecapStory.create(story: s1, recap: r2)
rs5 = RecapStory.create(story: s2, recap: r2)
rs6 = RecapStory.create(story: s1, recap: r4)
rs7 = RecapStory.create(story: s2, recap: r4)
rs8 = RecapStory.create(story: s1, recap: r5)
rs9 = RecapStory.create(story: s1, recap: r6)
